upstream_package_name: rofimoji
downstream_package_name: rofimoji

upstream_project_url: https://github.com/fdw/rofimoji
upstream_tag_template: google-cloud-functions-v{version}

specfile_path: rofimoji.spec

jobs:
  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-all

  - job: pull_from_upstream
    trigger: release
    dist_git_branches:
      - fedora-all

  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all
    allowed_pr_authors:
      - packit
      - mhayden
    allowed_committers:
      - packit
      - mhayden

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched